### ISSUE TITLE
v 1.1.1 bib2df() loses 1st bib entry

### ISSUE THREAD

**Issue by mhines-usgs** [ropensci/bib2df#45]
i'm seeing the bib2df() function lose or skip the first bibtex entry in the files I'm using v1.1.1

example file attached, rename to .bib, has 100 records 
[17 water and demand.txt](https://github.com/ropensci/bib2df/files/5804970/17.water.and.demand.txt)

```
library(bib2df)
path2file <- "17 water and demand.bib"
bib <- bib2df(file=path2file, separate_names = FALSE)
```

> nrow(bib)
[1] 99

**Comment by GilmourR** [comment]
Hi. Your bib file is malformed. It looks like it's output from Publish of Perish. I loaded your file into JabRef, ran Clean, and resaved it. I got 100 records on the cleaned file. I expect you still have significant cleaning to do on the bib file. Authors, journal titles and other items are incomplete. You could use JabRef to retrieve DOI's from CrossRef and then update the bibliometric information from those DOI. JabRef pulls the information from CrossRef, which would replace what you got from Google. On Windows, I have encoding issues with these files and have to transliterate the text to eliminate non-ascii characters. My tests indicate the issue is with humaniformat rather than bib2df. Good luck.

**Comment by mhines-usgs** [comment]
Oof, can you tell I'm new to this? thank you for letting me know. I did try another tool called RefManageR to take advantage of its merge function and somehow it was able to work through it, so I didn't realize, but yes that's the source of these files. Thank you for your suggestions on how to improve/fix it!
